### ISSUE TITLE
Compiling issues on M1 macs

### ISSUE THREAD

**Issue by luciansvnc** [tokenstreet-tech/react-native-idnow-videoident#738] opened 2023-01-23 17:33 UTC
I used these instructions https://tokenstreet-tech.github.io/react-native-idnow-videoident/docs/getting-started to add the library to react native my project but I am having issues compiling this on an M1 mac. It is compiling perfectly on a physical device but it fails with an arm64 architecture error on simulators. Is there anyway to fix this? Thanks!

**Comment by reichhartd** [comment] 2023-01-25 22:36
Hi @luciansvnc,
sorry for the late reply. We also use M1 Macs, and the issue you described is related to the build type `use_frameworks! linkage: :static`, which is mandatory for IDnow iOS SDK.
I will add the cause and a solution to the docs tomorrow, and link it in this issue.
Until then, you can take a look at the following code examples:

-   [Bare example app](https://github.com/tokenstreet-tech/react-native-idnow-videoident/blob/e42b2eb4644c8e6d6cab850adb567a8892d28966/examples/bare/ios/Podfile#L80-L83)
-   [Expo plugin](https://github.com/tokenstreet-tech/react-native-idnow-videoident/blob/e42b2eb4644c8e6d6cab850adb567a8892d28966/src/expo/withIosIdnowVideoIdentSdk.ts#L26-L32)

**Comment by reichhartd** [comment] 2023-01-27 17:01
https://tokenstreet-tech.github.io/react-native-idnow-videoident/docs/getting-started#ios-1
Does step 5 fix it for you?

**Comment by reichhartd** [comment] 2023-01-31 16:05
I will close the issue. If the problem still occurs, feel free to open it again.

**Closed by reichhartd** 2023-01-31 16:05 UTC
Labels: bug
